export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SEARCH_PRODUCTS: "SEARCH_PRODUCTS",
  FILTER_PRODUCTS: "FILTER_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
};
